"""
Master G-code generator.

Takes a list of PlacedPart objects (each with a parsed GcodePart and placement
info) and produces a single merged .nc file following the order-of-operations
merge rules and nearest-neighbor travel sort from the spec.
"""
import re
from datetime import datetime
from typing import Dict, List, Optional, Tuple

from collision import PlacedPart

# ── compiled patterns ─────────────────────────────────────────────────────────

_IJ = re.compile(r"([IJ])([+-]?\d*\.?\d+)")
_N_CODE = re.compile(r"^N\d+\s*")
_TOOL_CMT = re.compile(r"\(\s*Tool:\s*(.+?)\)", re.IGNORECASE)
_SPINDLE = re.compile(r"\bM03\b.*\bS(\d+)\b", re.IGNORECASE)
_S_WORD = re.compile(r"\bS(\d+(?:\.\d+)?)\b", re.IGNORECASE)
_MOTION_WORD = re.compile(r"[XYZIJKR]", re.IGNORECASE)
_G43_LINE = re.compile(r"\bG43\b", re.IGNORECASE)
_Z_RETRACT = re.compile(r"^G0?0\s+Z[+-]?\d*\.?\d+\s*$", re.IGNORECASE)


# ── public entry point ────────────────────────────────────────────────────────

def generate_master_gcode(placements: List[PlacedPart], settings: Dict) -> str:
    """
    Build a merged master G-code string from a list of placed parts.

    Order of operations:
      Walk pass indices 0, 1, 2... across all parts.
      At each index, group by tool number.
      Consecutive blocks with the same tool are merged (no tool change inserted).
      Within each merged block, segments are sorted by nearest-neighbor to
      minimise rapid-travel distance without violating per-part operation order.
    """
    adv = settings["advanced"]
    rail_w = float(adv["rail_width_mm"])
    bed_x = float(adv["bed_x_mm"])
    bed_y = float(adv["bed_y_mm"])
    edge_margin_in = float(adv.get("slot_edge_margin_in", 0.0))
    tool_capacity = int(adv.get("tool_capacity", 5))
    job_name = settings.get("job_name", "master_job")
    safe_z_info = settings.get("job_safe_z") or {}
    job_safe_z = float(safe_z_info.get("value") or adv.get("safe_z_clearance_mm", 25.4))
    safe_z_driver = safe_z_info.get("driven_by") or ""

    filenames = [p.part.filename for p in placements]
    all_tools: List[str] = []
    for p in placements:
        for gp in p.part.passes:
            if gp.tool_number not in all_tools:
                all_tools.append(gp.tool_number)

    # IQ Pro tool changer holds a fixed number of tools (default 5). A job that
    # needs more cannot be loaded on the machine, so fail loudly here.
    if len(all_tools) > tool_capacity:
        raise ValueError(
            f"Job needs {len(all_tools)} tools ({', '.join(all_tools)}) but the IQ Pro "
            f"tool changer holds only {tool_capacity}. Remove parts or reduce distinct tools."
        )

    # Material size for the nest = the full bed; Z = thickest placed stock.
    thicknesses = [p.part.material_thickness for p in placements
                   if p.part.material_thickness]
    material_z = max(thicknesses) if thicknesses else 0.0

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    out: List[str] = []
    _n = [0]

    def N(line: str) -> str:
        n = _n[0]
        _n[0] += 10
        return f"N{n} {line}"

    # ── file header ───────────────────────────────────────────────────────────
    # Mirror the Laguna IQ ATC VECTRIC post: Filename/Machine comments, the
    # ( Material Size) block, then a lean G54 boot (no G17/G71/G40/G49/G80/G90,
    # no G53). Extra informational comments are inert (parenthesised).
    out += [
        N(f"(Filename:  {job_name})"),
        N("(Machine:  Laguna IQ ATC)"),
        "( Material Size)",
        f"( X= {bed_x:.3f}, Y= {bed_y:.3f}, Z= {material_z:.3f})",
        f"(Generated by IQ Pro Layout Tool {now})",
        f"(Parts: {', '.join(filenames)})",
        f"(Instances: {len(placements)}  Tools: {', '.join(all_tools)})",
        f"(Safe Z: {job_safe_z / 25.4:.3f}\" — driven by {safe_z_driver})",
        N("G54"),
    ]

    # ── tool blocks ───────────────────────────────────────────────────────────
    blocks = _build_blocks(placements, rail_w, bed_y, edge_margin_in)

    for block_num, block in enumerate(blocks, start=1):
        tool = block["tool"]
        segs = _nearest_neighbor_sort(block["segments"])

        out += [
            "",
            f"( ---- {tool} pass {block_num} ---- )",
            N(f"{tool} M06"),
        ]
        if block["description"]:
            out.append(N(f"({block['description']})"))
        out.append(N(f"M03 S{block['spindle_speed']}"))
        current_spindle = block["spindle_speed"]
        for seg_idx, seg in enumerate(segs):
            if seg_idx > 0:
                out.append(N(f"G00 Z{job_safe_z:.4f}"))
            for ln in seg:
                s = ln.strip()
                if not s:
                    continue
                kept, current_spindle = _dedup_spindle(s, current_spindle)
                if kept:
                    out.append(N(kept))
        out += [
            N(f"G00 Z{job_safe_z:.4f}"),
            N("M05"),
        ]

    # ── park and end ──────────────────────────────────────────────────────────
    # IQ ATC dialect: retract Z, stop spindle, end. No G53 XY park.
    out += [
        "",
        "( ---- park ---- )",
        N(f"G00 Z{job_safe_z:.4f}"),
        N("M05"),
        N("M30"),
        "%",
    ]

    return "\n".join(out) + "\n"


# ── block building ────────────────────────────────────────────────────────────

def _build_blocks(placements: List[PlacedPart], rail_w: float, bed_y: float,
                  edge_margin_in: float = 0.0) -> list:
    """
    Produce an ordered list of tool blocks from all placements.

    Walk pass indices 0..max in order. At each index, group passes by tool.
    Append to the previous block when the tool matches; otherwise start a new one.
    This preserves each part's internal operation order while merging identical
    consecutive tools across parts.
    """
    max_passes = max((len(p.part.passes) for p in placements), default=0)
    blocks: list = []

    for idx in range(max_passes):
        by_tool: Dict[str, list] = {}
        for placed in placements:
            if idx < len(placed.part.passes):
                gp = placed.part.passes[idx]
                by_tool.setdefault(gp.tool_number, []).append((placed, gp.lines))

        for tool in sorted(by_tool):
            segs: list = []
            description = ""
            spindle_speed = 18000

            for placed, raw_lines in by_tool[tool]:
                if not description:
                    description = _tool_comment(raw_lines)
                spd = _spindle_speed(raw_lines)
                if spd:
                    spindle_speed = spd
                body = _extract_body(raw_lines)
                params = _transform_params(placed, rail_w, bed_y, edge_margin_in)
                segs.append([_transform_line(ln, params) for ln in body])

            if blocks and blocks[-1]["tool"] == tool:
                blocks[-1]["segments"].extend(segs)
            else:
                blocks.append({
                    "tool": tool,
                    "description": description,
                    "spindle_speed": spindle_speed,
                    "segments": segs,
                })

    return blocks


# ── pass helpers ──────────────────────────────────────────────────────────────

def _tool_comment(lines: List[str]) -> str:
    for line in lines:
        m = _TOOL_CMT.search(line)
        if m:
            return m.group(1).strip()
    return ""


def _spindle_speed(lines: List[str]) -> Optional[int]:
    for line in lines:
        m = _SPINDLE.search(line)
        if m:
            return int(m.group(1))
    return None


def _dedup_spindle(line: str, current: Optional[int]) -> Tuple[Optional[str], Optional[int]]:
    """
    Suppress redundant spindle-speed commands within a tool block.

    `current` is the spindle speed already commanded (and still running) at this
    point in the block. Returns (output_line, new_current):
      - S-word equals `current` (redundant):
          * spindle-only line (no motion words) -> drop entirely -> (None, current)
          * motion line -> strip the redundant S-word, keep the motion
      - S-word differs -> keep the line, update current to the new speed
      - no S-word -> returned unchanged
    """
    m = _S_WORD.search(line)
    if not m:
        return line, current
    speed = int(float(m.group(1)))
    if current is not None and speed == current:
        if not _MOTION_WORD.search(line):
            return None, current
        stripped = re.sub(r"\s{2,}", " ", _S_WORD.sub("", line)).strip()
        return stripped, current
    return line, speed


def _extract_body(lines: List[str]) -> List[str]:
    """
    Return the movement lines from a pass: everything after M03 and before
    the trailing G53/M05/M30 retract block. Strips N-codes and any G43 lines
    (G43 is emitted once per tool block by the generator; source copies are dropped).
    Trailing Z-only retracts are also stripped so the generator can emit a single
    clean G00 Z[job_safe_z] between part segments.
    """
    body: List[str] = []
    in_body = False
    for line in lines:
        s = line.strip()
        if not in_body:
            if re.search(r"\bM03\b", s, re.IGNORECASE):
                in_body = True
        else:
            if (s == "%" or
                    re.search(r"\bM05\b|\bM30\b", s, re.IGNORECASE) or
                    (re.search(r"\bG53\b", s, re.IGNORECASE) and "Z" in s.upper())):
                break
            if s and not _G43_LINE.search(s):
                body.append(_N_CODE.sub("", s))
    while body and _Z_RETRACT.match(body[-1]):
        body.pop()
    return body


# ── coordinate transformation ─────────────────────────────────────────────────

def _transform_params(placed: PlacedPart, rail_w: float, bed_y: float,
                      edge_margin_in: float = 0.0) -> dict:
    """
    Pre-compute per-placement transform constants (single rail, additive offset).

    VCarve X → G-code X output → machine Y direction
    VCarve Y → G-code Y output → machine X direction

    The single rail is a proper 180°-class rotation of the VCarve geometry
    (det(Jacobian) = +1): the X file-axis is mirrored so that, combined with the
    X/Y axis swap, handedness is preserved.

      output_X = slot_mark - vcarve_X        (G-code X = machine Y, reversed)
      output_Y = rail_w + vcarve_Y           (G-code Y = machine X, additive)
    """
    slot_mark = bed_y - (placed.slot_inches + edge_margin_in) * 25.4
    return {"b_x": True,  "x": slot_mark,
            "b_y": False, "y": rail_w}


def _transform_line(line: str, p: dict) -> str:
    """
    Apply placement transform to a single G-code line.

    Axis mapping: VCarve X (file X word) → machine Y (output Y word)
                  VCarve Y (file Y word) → machine X (output X word)
    Arc offsets:  file I (VCarve-X direction) → output J (machine-Y direction)
                  file J (VCarve-Y direction) → output I (machine-X direction)

    p['b_x']/p['x']: mirror flag and constant for the VCarve-X → machine-Y transform
    p['b_y']/p['y']: mirror flag and constant for the VCarve-Y → machine-X transform
    Comments and G53 machine-coord lines are returned unchanged.
    """
    s = line.strip()
    if not s or s.startswith("("):
        return s
    if re.search(r"\bG53\b", s, re.IGNORECASE):
        return s

    result = s
    x_mirror = p["b_x"]
    y_mirror = p["b_y"]

    # Arc direction: the axis swap (file X→output Y, file Y→output X) contributes one
    # orientation flip. Combined with the per-axis mirrors, det(Jacobian) < 0 (swap
    # needed) when x_mirror == y_mirror (both same sign → product positive → det negative).
    # Both rails are proper rotations (exactly one axis mirrored → det > 0 → no swap):
    #   A rail (b_x=True,  b_y=False), B rail (b_x=False, b_y=True).
    if x_mirror == y_mirror:
        if re.search(r"\bG02\b", result, re.IGNORECASE):
            result = re.sub(r"\bG02\b", "G03", result, flags=re.IGNORECASE)
        elif re.search(r"\bG03\b", result, re.IGNORECASE):
            result = re.sub(r"\bG03\b", "G02", result, flags=re.IGNORECASE)

    # Arc offsets: file I (VCarve-X direction) → machine-Y → output J (negate if x_mirror)
    #              file J (VCarve-Y direction) → machine-X → output I (negate if y_mirror)
    # Use placeholders to avoid cross-contamination between the two substitutions.
    result = re.sub(r"I([+-]?\d*\.?\d+)",
                    lambda m: f"__J__{-float(m.group(1)):.4f}" if x_mirror
                    else f"__J__{float(m.group(1)):.4f}", result)
    result = re.sub(r"J([+-]?\d*\.?\d+)",
                    lambda m: f"__I__{-float(m.group(1)):.4f}" if y_mirror
                    else f"__I__{float(m.group(1)):.4f}", result)
    result = result.replace("__J__", "J").replace("__I__", "I")

    # Coordinates: file X (VCarve X) → machine Y → output Y word
    #              file Y (VCarve Y) → machine X → output X word
    result = re.sub(r"X([+-]?\d*\.?\d+)",
                    lambda m: f"__Y__{p['x'] - float(m.group(1)):.4f}" if x_mirror
                    else f"__Y__{float(m.group(1)) + p['x']:.4f}", result)
    result = re.sub(r"Y([+-]?\d*\.?\d+)",
                    lambda m: f"__X__{p['y'] - float(m.group(1)):.4f}" if y_mirror
                    else f"__X__{float(m.group(1)) + p['y']:.4f}", result)
    result = result.replace("__Y__", "Y").replace("__X__", "X")

    return result


# ── nearest-neighbour travel sort ─────────────────────────────────────────────

def _first_xy(lines: List[str]) -> Tuple[float, float]:
    x = y = None
    for line in lines:
        for axis, val in re.findall(r"([XY])([+-]?\d*\.?\d+)", line):
            if axis == "X" and x is None:
                x = float(val)
            elif axis == "Y" and y is None:
                y = float(val)
        if x is not None and y is not None:
            break
    return (x or 0.0, y or 0.0)


def _last_xy(lines: List[str]) -> Tuple[float, float]:
    return _first_xy(list(reversed(lines)))


def _nearest_neighbor_sort(segs: list) -> list:
    """Greedy nearest-neighbour ordering to minimise rapid travel between segments."""
    if len(segs) <= 1:
        return segs
    remaining = list(segs)
    result = [remaining.pop(0)]
    last = _last_xy(result[0])
    while remaining:
        best_i, best_d = 0, float("inf")
        for i, seg in enumerate(remaining):
            dx, dy = _first_xy(seg)[0] - last[0], _first_xy(seg)[1] - last[1]
            d = (dx * dx + dy * dy) ** 0.5
            if d < best_d:
                best_d, best_i = d, i
        result.append(remaining.pop(best_i))
        last = _last_xy(result[-1])
    return result
